Repository orval-labs/orval, pull requests merged in 2023-12, with the labels that each got.

#1100 fix(query): suspense query generation
  packages/query/src/index.ts
Labels: bug

#1103 fix(core): readonly array schema value
  packages/core/src/getters/array.ts
  samples/basic/api/endpoints/petstoreFromFileSpec.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithConfig.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/basic/api/model/index.ts
  samples/basic/api/model/listPetsParams.ts
  samples/react-query/basic/src/api/model/catType.ts
  samples/react-query/basic/src/api/model/dachshundBreed.ts
  samples/react-query/basic/src/api/model/dogType.ts
  samples/react-query/basic/src/api/model/labradoodleBreed.ts
  samples/react-query/basic/src/api/model/petCallingCode.ts
  samples/react-query/basic/src/api/model/petCountry.ts
  samples/react-query/custom-client/src/api/model/petCallingCode.ts
  samples/react-query/custom-client/src/api/model/petCountry.ts
  samples/react-query/form-data-mutator/models/petCallingCode.ts
  samples/react-query/form-data-mutator/models/petCountry.ts
  samples/react-query/form-data/models/petCallingCode.ts
  samples/react-query/form-data/models/petCountry.ts
  samples/react-query/form-url-encoded-mutator/models/petCallingCode.ts
  samples/react-query/form-url-encoded-mutator/models/petCountry.ts
  samples/react-query/form-url-encoded/endpoints.ts
  samples/react-query/form-url-encoded/models/index.ts
  samples/react-query/form-url-encoded/models/petCallingCode.ts
  samples/react-query/form-url-encoded/models/petCountry.ts
  samples/react-query/hook-mutator/models/petCallingCode.ts
  samples/react-query/hook-mutator/models/petCountry.ts
Labels: bug

#1109 fix: crash when no response mediaType
  packages/core/src/getters/res-req-types.ts
Labels: bug

#1110 fix(core): use non-barrel schema file imports when using split-tags mode
  packages/core/src/writers/split-tags-mode.ts
Labels: bug

#1104 Add option to configure generated schema item suffix
  packages/core/src/getters/array.ts
  packages/core/src/types.ts
  packages/orval/src/utils/options.ts
Labels: enhancement

#1115 fix(core): add missing properties in subschemas to fix TS error
  packages/core/src/getters/combine.ts
  samples/react-query/basic/src/api/model/dog.ts
  samples/react-query/basic/src/api/model/pet.ts
Labels: bug

#1121 docs: Update `output.client` description
  docs/src/pages/reference/configuration/output.md
Labels: documentation

#1122 fix(core): Fixed condition for using `barrel` import in `split-tags` mode
  packages/core/src/writers/split-tags-mode.ts
Labels: bug

#1124 docs: Updated sample code for `output.mode`
  docs/src/pages/reference/configuration/output.md
Labels: documentation

#1123 docs: Add document for `output.indexFiles`
  docs/src/pages/reference/configuration/output.md
Labels: documentation

#1128 docs: fix broken link to `OpenAPIObject`
  docs/src/pages/reference/configuration/input.md
Labels: documentation

#1129 docs: fix url for `GeneratorVerbOptions` type
  docs/src/pages/reference/configuration/output.md
Labels: documentation
