Repository orval-labs/orval, pull requests merged in 2023-11, with the labels that each got.

#1003 feat(security): upgrade dependencies for security CVE's
  .gitignore
  package.json
  packages/core/package.json
  packages/core/src/utils/validator.ts
  packages/msw/package.json
  packages/orval/package.json
  yarn.lock
Labels: dependencies, javascript

#1004 feat: disable minification
  packages/angular/package.json
  packages/axios/package.json
  packages/core/package.json
  packages/msw/package.json
  packages/orval/package.json
  packages/query/package.json
  packages/swr/package.json
  packages/zod/package.json
Labels: enhancement

#1006 docs(config): mutationOptions
  docs/src/pages/reference/configuration/output.md
Labels: documentation

#1007 feat: upgraded msw to 2.0
  .github/workflows/tests.yaml
  packages/msw/package.json
  packages/msw/src/index.ts
  samples/angular-app/package.json
  samples/angular-app/src/api/endpoints/pets/pets.msw.ts
  samples/angular-app/src/api/mocks/mock.service.ts
  samples/angular-app/yarn.lock
  samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/basic/package.json
  samples/basic/yarn.lock
  samples/react-app-with-swr/package.json
  samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-app-with-swr/src/mock.ts
  samples/react-app-with-swr/yarn.lock
  samples/react-app/package.json
  samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-app/src/mock.ts
  samples/react-app/yarn.lock
  samples/react-query/basic/package.json
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-query/basic/src/mock.ts
  samples/react-query/basic/yarn.lock
  samples/react-query/custom-client/package.json
  samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-query/custom-client/src/mock.ts
  samples/react-query/custom-client/yarn.lock
  samples/svelte-query/package.json
  samples/svelte-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/svelte-query/src/mocks/browser.ts
  samples/svelte-query/yarn.lock
  samples/vue-query/package.json
  samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/vue-query/src/mock.ts
  samples/vue-query/yarn.lock
  tests/package.json
  tests/yarn.lock
  yarn.lock
Labels: dependencies, javascript

#979 Don't use name with suffix when resolving discriminators
  packages/core/src/getters/discriminators.ts
Labels: enhancement

#876 fix(schemas): detect duplicate schema names and throw
  packages/core/src/writers/schemas.ts
Labels: enhancement

#1035 Fix(MSW):non ref enum const
  packages/msw/src/getters/object.ts
  packages/msw/src/getters/scalar.ts
Labels: bug

#1042 fix(MSW): accounted for properties with the same name
  packages/msw/src/getters/combine.ts
  packages/msw/src/getters/object.ts
  packages/msw/src/getters/scalar.ts
  packages/msw/src/mocks.ts
  packages/msw/src/resolvers/value.ts
Labels: bug

#1044 fix: uppercase method verbs
  packages/core/src/generators/options.ts
  packages/core/src/utils/assertion.ts
  tests/mutators/custom-client.ts
Labels: bug

#1051 fix[zod]: enable multiple properties of array consts
  packages/core/package.json
  packages/zod/package.json
  packages/zod/src/index.ts
  tests/configs/zod.config.ts
  tests/specifications/arrays.yaml
Labels: bug

#1045 Add option to enable Zod type coercion for query params
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/zod/package.json
  packages/zod/src/index.ts
  packages/zod/src/zod.test.ts
  tests/configs/zod-parameters.config.ts
  tests/package.json
  tests/specifications/parameters.yaml
Labels: enhancement

#1050 fix(zod): proper date handling
  packages/zod/src/index.ts
  tests/specifications/circular.yaml
Labels: documentation

#1052 fix(zod): array min max issues
  packages/zod/src/index.ts
  tests/specifications/circular.yaml
Labels: bug

#1058 feat: add optional configuration parameter to generate native Typescript enums
  docs/src/pages/reference/configuration/output.md
  packages/core/src/generators/schema-definition.ts
  packages/core/src/getters/enum.ts
  packages/core/src/getters/query-params.ts
  packages/core/src/resolvers/object.ts
  packages/core/src/types.ts
  packages/orval/src/utils/options.ts
Labels: enhancement

#931 Fix Query parameters reactivity in Vue
  .github/workflows/tests.yaml
  .node-version
  .nvmrc
  .prettierignore
  .prettierrc.json
  package.json
  packages/core/src/generators/options.ts
  packages/core/src/getters/discriminators.ts
  packages/core/src/getters/object.ts
  packages/core/src/writers/schemas.ts
  packages/query/package.json
  packages/query/src/index.test.ts
  packages/query/src/index.ts
  samples/react-app-with-swr/src/mock.ts
  samples/react-app/src/mock.ts
  samples/react-query/basic/src/mock.ts
  samples/react-query/custom-client/src/mock.ts
  samples/svelte-query/src/api/transformer/add-version.cjs
  samples/svelte-query/src/app.css
  samples/svelte-query/src/mocks/browser.ts
  samples/svelte-query/src/mocks/server.ts
  samples/vue-query/package.json
  samples/vue-query/petstore.yaml
  samples/vue-query/public/mockServiceWorker.js
  samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/vue-query/src/api/model/listPetsParams.ts
  samples/vue-query/src/components/pet.spec.ts
  samples/vue-query/src/components/pet.vue
  samples/vue-query/src/components/pets.spec.ts
  samples/vue-query/src/components/pets.vue
  samples/vue-query/src/mock.ts
  samples/vue-query/src/mocks/handlers.ts
  samples/vue-query/src/mocks/server.ts
  samples/vue-query/src/setupTests.ts
  samples/vue-query/tsconfig.json
  samples/vue-query/vite.config.ts
  samples/vue-query/yarn.lock
  scripts/update-samples.mjs
  tests/configs/vue-query.config.ts
  yarn.lock
Labels: bug

#1081 fix: enum string escape can be nullable
  packages/core/src/utils/string.ts
  tests/configs/default.config.ts
  tests/specifications/null-type-v3-0.yaml
Labels: bug
