Repository orval-labs/orval, pull requests merged in 2024-04, with the labels that each got.

#1281 feat: support runtime delay functions
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/mock/src/delay.ts
  packages/mock/src/msw/index.ts
  tests/configs/default.config.ts
Labels: mock

#1294 fix: schema type integer
  packages/core/src/getters/res-req-types.ts
Labels: enhancement

#1284 feat: generate mocks for all responses
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/mock/src/msw/index.ts
  packages/mock/src/msw/mocks.ts
  tests/configs/default.config.ts
Labels: mock

#1305 fix: accumulate discriminator mapping keys
  packages/core/src/getters/discriminators.ts
  samples/basic/api/endpoints/petstoreFromFileSpec.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithConfig.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/basic/api/model/index.ts
  samples/basic/api/model/listPetsParams.ts
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/react-query/form-url-encoded/endpoints.ts
  samples/react-query/form-url-encoded/models/index.ts
  samples/react-query/form-url-encoded/models/petCallingCode.ts
  samples/react-query/form-url-encoded/models/petCountry.ts
Labels: bug

#1311 fix(zod): handle schema type array correctly
  packages/zod/src/index.ts
Labels: zod

#1313 fix(mock/msw): override response if it's false as well
  packages/mock/src/msw/index.ts
Labels: mock

#1315 chore(docs): correct link for faker mock formats, correct nesting level
  docs/src/pages/reference/configuration/output.md
Labels: documentation

#1320 feat: added `output.fileExtension` option to possible specifying the extension for the generated file.
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/core/src/writers/single-mode.ts
  packages/core/src/writers/split-mode.ts
  packages/core/src/writers/split-tags-mode.ts
  packages/core/src/writers/tags-mode.ts
  packages/orval/src/utils/options.ts
Labels: enhancement

#1321 feat(core): add option to apply `biome` to generated files
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/orval/src/bin/orval.ts
  packages/orval/src/utils/options.ts
  packages/orval/src/write-specs.ts
Labels: enhancement

#1340 Feature/zod coerce select types
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/zod/src/index.ts
Labels: zod

#1341 fix: valid syntax when anyOf is present on querystring
  packages/core/src/getters/combine.ts
  tests/configs/default.config.ts
  tests/specifications/any-of.yaml
Labels: bug
