Repository orval-labs/orval, pull requests merged in 2024-10, with the labels that each got.

#1659 fix: required of parent schema not considered in allOf #1570
  packages/core/src/getters/combine.ts
  packages/mock/src/faker/getters/combine.ts
  tests/specifications/polymorphic.yaml
Labels: bug

#1663 fix(msw): fix broken mocks when using 'allOf' within 'anyOf' and using a shared schema
  packages/mock/src/faker/resolvers/value.ts
  tests/specifications/any-of.yaml
Labels: bug, msw

#1673 fix: faker recursive reference pascal sanitation
  packages/mock/src/faker/getters/combine.ts
  packages/mock/src/faker/getters/object.ts
  packages/mock/src/faker/getters/scalar.ts
Labels: mock
