Repository orval-labs/orval, pull requests merged in 2024-06, with the labels that each got.

#1429 fix(zod): all http responses can now be generated
  packages/zod/src/index.ts
Labels: zod

#1427 chore(deps): update deps for `react-query` sample
  samples/react-query/form-url-encoded/yarn.lock
Labels: dependencies

#1426 feat: add `input.filters.schemas` option
  docs/src/pages/reference/configuration/input.md
  packages/core/src/generators/schema-definition.ts
  packages/core/src/types.ts
  packages/orval/src/import-open-api.ts
  tests/configs/default.config.ts
Labels: enhancement

#1437 fix(msw): correctly generate integer enum mocks
  packages/mock/src/faker/getters/scalar.ts
Labels: bug

#1353 feat: add new client `fetch`
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/fetch/README.md
  packages/fetch/package.json
  packages/fetch/src/index.ts
  packages/fetch/tsconfig.json
  packages/orval/package.json
  packages/orval/src/client.ts
  tests/configs/fetch.config.ts
  tests/package.json
  yarn.lock
Labels: enhancement

#1416 fix: take optional request body into account when creating form data
  packages/core/src/getters/res-req-types.ts
  tests/configs/swr.config.ts
  tests/specifications/form-data-optional-request.yaml
Labels: bug

#1442 fix(msw): also split allof objects
  packages/mock/src/faker/resolvers/value.ts
Labels: mock

#1443 fix(zod): treat `additionalProperties` keyword
  packages/zod/src/index.ts
  packages/zod/src/zod.test.ts
  tests/configs/zod.config.ts
Labels: zod

#1456 fix(msw): correctly add imports for enum references
  packages/mock/src/faker/getters/scalar.ts
  tests/configs/mock.config.ts
  tests/specifications/enum-refs.yaml
Labels: mock

#1459 fix(msw): correctly generate ref'd examples
  packages/mock/src/msw/mocks.ts
  tests/configs/swr.config.ts
  tests/specifications/examples.yaml
Labels: mock

#1457 feat(fetch): support custom mutator
  packages/fetch/src/index.ts
  samples/next-app-with-fetch/app/gen/models/cat.ts
  samples/next-app-with-fetch/app/gen/models/catType.ts
  samples/next-app-with-fetch/app/gen/models/createPetsBodyItem.ts
  samples/next-app-with-fetch/app/gen/models/dachshund.ts
  samples/next-app-with-fetch/app/gen/models/dachshundBreed.ts
  samples/next-app-with-fetch/app/gen/models/dog.ts
  samples/next-app-with-fetch/app/gen/models/dogType.ts
  samples/next-app-with-fetch/app/gen/models/error.ts
  samples/next-app-with-fetch/app/gen/models/index.ts
  samples/next-app-with-fetch/app/gen/models/labradoodle.ts
  samples/next-app-with-fetch/app/gen/models/labradoodleBreed.ts
  samples/next-app-with-fetch/app/gen/models/listPetsParams.ts
  samples/next-app-with-fetch/app/gen/models/pet.ts
  samples/next-app-with-fetch/app/gen/models/petCallingCode.ts
  samples/next-app-with-fetch/app/gen/models/petCountry.ts
  samples/next-app-with-fetch/app/gen/models/pets.ts
  samples/next-app-with-fetch/app/gen/pets/pets.msw.ts
  samples/next-app-with-fetch/app/gen/pets/pets.ts
  samples/next-app-with-fetch/custom-fetch.ts
  samples/next-app-with-fetch/orval.config.ts
Labels: enhancement

#1461 chore(fetch): add mutator test for `fetch` client
  tests/configs/fetch.config.ts
  tests/mutators/custom-fetch.ts
Labels: enhancement

#1466 fix: use unknown instead of any for additional properties
  packages/core/src/getters/object.ts
Labels: bug

#1470 feat(fetch): include status code in `fetch` client response
  packages/fetch/src/index.ts
  samples/next-app-with-fetch/app/gen/pets/pets.ts
  samples/next-app-with-fetch/app/pets.tsx
  samples/next-app-with-fetch/custom-fetch.ts
Labels: enhancement, fetch

#1476 docs(fetch): add guide for `fetch` client
  docs/src/manifests/manifest.json
  docs/src/pages/guides/fetch.md
Labels: documentation, fetch

#1478 fix: punycode deprecation warning
  package.json
  yarn.lock
Labels: enhancement, dependencies

#1484 feat: add override function to empty response mocks
  packages/mock/src/msw/index.ts
  samples/angular-app/src/api/endpoints/pets/pets.msw.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/next-app-with-fetch/app/gen/pets/pets.msw.ts
  samples/react-app-with-swr/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-app/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/react-query/custom-client/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/svelte-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.msw.ts
  tests/specifications/any-of.yaml
Labels: mock

#1489 chore(swr): extract http client in `swr`
  packages/swr/src/client.ts
  packages/swr/src/index.ts
Labels: enhancement

#1491 feat(mock): infer type from enum values for string and number
  packages/mock/src/faker/getters/scalar.ts
  tests/configs/mock.config.ts
  tests/specifications/typelessEnum.yaml
Labels: mock
