Repository orval-labs/orval, pull requests merged in 2024-02, with the labels that each got.

#1196 chore: bump `Angular` packages to v17 in `tests`
  tests/package.json
  tests/yarn.lock
Labels: dependencies

#1194 revert: afterAllFilesWritten
  docs/src/pages/reference/configuration/hooks.md
Labels: documentation

#1200 fix(angular): avoid `Angular` type error when `nullable`
  packages/core/src/getters/scalar.ts
Labels: bug

#1205 fix(msw): fixed imports of `split-tags`, `tags`, and `split` mode
  packages/core/src/writers/split-mode.ts
  packages/core/src/writers/split-tags-mode.ts
  packages/core/src/writers/tags-mode.ts
Labels: bug

#1209 fix: useMutation still appears even if false
  packages/query/src/index.ts
Labels: bug

#1212 fix: useQuery improve override logic
  packages/query/src/index.ts
Labels: bug

#1216 chore(zod): add petstore tests for each mode to `zod`
  tests/configs/zod.config.ts
Labels: enhancement

#1217 fix(msw): changed naming convention for response mock functions to avoid function name conflicts
  packages/mock/src/msw/index.ts
Labels: bug

#1226 docs: fix format in samples
  samples/basic/api/endpoints/petstoreFromFileSpec.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithConfig.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/basic/api/model/index.ts
  samples/basic/api/model/listPetsParams.ts
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/react-query/form-url-encoded/endpoints.ts
  samples/react-query/form-url-encoded/models/index.ts
  samples/react-query/form-url-encoded/models/petCallingCode.ts
  samples/react-query/form-url-encoded/models/petCountry.ts
Labels: bug

#1225 feat(swr): add `swrMutationOptions` property to `output.override.swr`
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/swr/src/index.ts
  tests/configs/swr.config.ts
Labels: enhancement

#1229 fix: TypeError custom override
  packages/mock/src/msw/index.ts
  tests/configs/default.config.ts
Labels: bug

#1231 feat: jsdoc block tags
  packages/core/src/utils/doc.ts
  samples/basic/api/endpoints/petstoreFromFileSpec.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithConfig.ts
  samples/basic/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/basic/api/model/pet.ts
  samples/basic/api/model/pets.ts
  samples/basic/petstore.yaml
Labels: enhancement

#1238 fix(core): NPE check in validator
  packages/core/src/utils/validator.ts
Labels: bug
