Repository orval-labs/orval, pull requests merged in 2024-01, with the labels that each got.

#1130 fix: avoid duplicate variable name in `swr` function
  packages/swr/src/index.ts
Labels: bug

#1141 chore: change `pretty-quick` in format library to `lint-stage`
  .lintstagedrc.json
  package.json
  yarn.lock
Labels: enhancement

#1148 feat: implement function generation using `useSWRMutation`
  packages/swr/src/index.ts
Labels: enhancement

#1125 fix: adjust SecondParameter utility type
  packages/axios/src/index.ts
  packages/query/src/index.ts
  packages/swr/src/index.ts
Labels: enhancement

#1157 fix: handle nordic characters
  packages/core/src/utils/case.test.ts
  packages/core/src/utils/case.ts
Labels: bug

#1158 chore: upgrade `prettier` to `3.2.2`
  package.json
  packages/core/src/generators/options.ts
  packages/core/src/types.ts
  packages/core/src/utils/logger.ts
  packages/core/src/utils/merge-deep.ts
  packages/core/src/writers/target-tags.ts
  packages/orval/src/client.ts
  packages/orval/src/import-open-api.ts
  packages/orval/src/utils/options.ts
  packages/orval/src/utils/watcher.ts
  packages/orval/src/write-specs.ts
  packages/query/src/index.ts
  packages/swr/src/index.ts
  packages/zod/src/index.ts
  samples/angular-app/src/index.html
  samples/basic/index.html
  samples/nx-fastify-react/apps/api/src/main.ts
  samples/nx-fastify-react/apps/api/src/type.d.ts
  samples/nx-fastify-react/apps/app/.babelrc
  samples/nx-fastify-react/apps/app/src/api/endpoints/petstoreAPI.ts
  samples/nx-fastify-react/apps/app/src/api/mutator/custom-instance.ts
  samples/nx-fastify-react/apps/app/src/app/app.tsx
  samples/nx-fastify-react/apps/app/src/index.html
  samples/nx-fastify-react/apps/app/src/main.tsx
  samples/react-app-with-swr/public/index.html
  samples/react-app-with-swr/src/App.tsx
  samples/react-app/public/index.html
  samples/react-query/basic/public/index.html
  samples/react-query/basic/src/App.tsx
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/react-query/basic/src/api/model/catType.ts
  samples/react-query/basic/src/api/model/dachshundBreed.ts
  samples/react-query/basic/src/api/model/dogType.ts
  samples/react-query/basic/src/api/model/labradoodleBreed.ts
  samples/react-query/basic/src/api/model/petCallingCode.ts
  samples/react-query/basic/src/api/model/petCountry.ts
  samples/react-query/custom-client/public/index.html
  samples/react-query/custom-client/src/App.tsx
  samples/react-query/custom-client/src/api/model/petCallingCode.ts
  samples/react-query/custom-client/src/api/model/petCountry.ts
  samples/react-query/form-data-mutator/models/petCallingCode.ts
  samples/react-query/form-data-mutator/models/petCountry.ts
  samples/react-query/form-data/models/petCallingCode.ts
  samples/react-query/form-data/models/petCountry.ts
  samples/react-query/form-url-encoded-mutator/models/petCallingCode.ts
  samples/react-query/form-url-encoded-mutator/models/petCountry.ts
  samples/react-query/form-url-encoded/models/petCallingCode.ts
  samples/react-query/form-url-encoded/models/petCountry.ts
  samples/react-query/hook-mutator/models/petCallingCode.ts
  samples/react-query/hook-mutator/models/petCountry.ts
  samples/svelte-query/src/app.html
  samples/vue-query/index.html
  yarn.lock
Labels: dependencies

#1160 Fix #1153: Fix native TS enums
  packages/core/src/getters/enum.ts
Labels: bug

#1163 feat: show error stack traces
  packages/core/src/utils/logger.ts
  packages/orval/src/bin/orval.ts
  packages/orval/src/generate.ts
  packages/orval/src/index.ts
  packages/orval/src/utils/executeHook.ts
  packages/orval/src/utils/watcher.ts
Labels: enhancement

#1168 build: enable sourcemaps
  packages/angular/package.json
  packages/axios/package.json
  packages/core/package.json
  packages/mock/package.json
  packages/orval/package.json
  packages/query/package.json
  packages/swr/package.json
  packages/zod/package.json
  tsconfig.base.json
Labels: enhancement

#1170 fix: openapi 3.1 schemas with multiple types
  packages/core/src/getters/combine.ts
  packages/core/src/getters/object.ts
Labels: bug

#1169 fix: add option for adding missing props to union types, fix duplicate props
  packages/angular/src/index.ts
  packages/axios/src/index.ts
  packages/core/src/generators/interface.ts
  packages/core/src/generators/schema-definition.ts
  packages/core/src/generators/verbs-options.ts
  packages/core/src/getters/array.ts
  packages/core/src/getters/body.ts
  packages/core/src/getters/combine.ts
  packages/core/src/getters/props.ts
  packages/core/src/getters/query-params.test.ts
  packages/core/src/getters/query-params.ts
  packages/core/src/getters/ref.ts
  packages/core/src/getters/scalar.ts
  packages/core/src/resolvers/object.ts
  packages/core/src/types.ts
  packages/mock/src/faker/getters/scalar.ts
  packages/mock/src/msw/mocks.ts
  packages/orval/src/import-open-api.ts
  packages/orval/src/utils/options.ts
  packages/query/src/index.ts
  packages/swr/src/index.ts
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  samples/react-query/basic/src/api/model/dog.ts
  samples/react-query/basic/src/api/model/pet.ts
Labels: bug

#1174 chore: update openapi types
  packages/core/package.json
  packages/core/src/generators/component-definition.ts
  packages/core/src/generators/interface.ts
  packages/core/src/generators/parameter-definition.ts
  packages/core/src/generators/schema-definition.ts
  packages/core/src/generators/verbs-options.ts
  packages/core/src/getters/array.ts
  packages/core/src/getters/body.ts
  packages/core/src/getters/combine.ts
  packages/core/src/getters/discriminators.ts
  packages/core/src/getters/object.ts
  packages/core/src/getters/operation.test.ts
  packages/core/src/getters/operation.ts
  packages/core/src/getters/parameters.ts
  packages/core/src/getters/query-params.test.ts
  packages/core/src/getters/query-params.ts
  packages/core/src/getters/ref.ts
  packages/core/src/getters/res-req-types.ts
  packages/core/src/getters/response.ts
  packages/core/src/getters/scalar.ts
  packages/core/src/resolvers/object.ts
  packages/core/src/resolvers/ref.ts
  packages/core/src/resolvers/value.ts
  packages/core/src/types.ts
  packages/core/src/utils/assertion.ts
  packages/core/src/utils/logger.ts
  packages/core/src/utils/open-api-converter.ts
  packages/core/src/utils/validator.ts
  packages/mock/package.json
  packages/mock/src/faker/constants.ts
  packages/mock/src/faker/getters/object.ts
  packages/mock/src/faker/resolvers/value.ts
  packages/mock/src/msw/mocks.ts
  packages/mock/src/types.ts
  packages/orval/package.json
  packages/orval/src/api.ts
  packages/orval/src/import-open-api.ts
  packages/orval/src/utils/options.ts
  packages/orval/src/write-specs.ts
  packages/zod/src/index.ts
  samples/react-query/basic/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
  types/swagger2openapi.d.ts
  yarn.lock
Labels: dependencies

#1175 feat: support for prefixItems
  packages/core/src/getters/array.ts
  tests/configs/default.config.ts
  tests/specifications/example-v3-1.yaml
Labels: enhancement

#1179 fix: reproducible typescript output (#1159)
  packages/orval/src/import-specs.ts
Labels: enhancement

#1178 feat: Only import formData override if it is used in file
  packages/core/src/generators/verbs-options.ts
Labels: enhancement

#1180 feat: support for const types
  packages/core/src/generators/interface.ts
  packages/core/src/getters/object.ts
  tests/specifications/example-v3-1.yaml
Labels: enhancement

#1182 feat(msw): separated mock handler and made it reusable
  packages/core/src/types.ts
  packages/core/src/writers/target-tags.ts
  packages/core/src/writers/target.ts
  packages/mock/src/msw/index.ts
  packages/orval/src/client.ts
Labels: enhancement

#1165 feat(msw): possible to overwrite value when creating an `object` with `msw` mock
  packages/mock/src/faker/getters/object.ts
  packages/mock/src/msw/index.ts
Labels: enhancement

#1171 feat(msw): define the return value type in the `msw` mock function.
  packages/core/src/writers/split-mode.ts
  packages/core/src/writers/split-tags-mode.ts
  packages/core/src/writers/tags-mode.ts
  packages/mock/src/msw/index.ts
Labels: enhancement

#1184 fix: define default value for `msw` mock orverride
  packages/mock/src/msw/index.ts
Labels: enhancement

#1186 feat(msw): possible to value of the mock handler function overridable
  packages/core/src/writers/target-tags.ts
  packages/core/src/writers/target.ts
  packages/mock/src/msw/index.ts
Labels: enhancement

#1181 feat: don't inject generated files into hook command
  docs/src/pages/reference/configuration/hooks.md
  packages/core/src/types.ts
  packages/orval/src/utils/executeHook.ts
  packages/orval/src/utils/options.ts
Labels: enhancement

#1105 RFC: feat(query): add shouldExportMutatorHooks option
  docs/src/pages/reference/configuration/output.md
  packages/core/src/types.ts
  packages/orval/src/utils/options.ts
  packages/query/src/index.ts
  packages/query/src/utils.ts
Labels: enhancement
